#!/usr/bin/env ruby

config_path = File.expand_path(File.dirname(__FILE__))
  
`ln -s #{config_path}/.emacs ~/.emacs`
`mkdir -p ~/.emacs.d`

Dir.glob(".emacs.d/*").each do |file|
  file = File.basename(file)
  `ln -s #{config_path}/.emacs.d/#{file} ~/.emacs.d/#{file}`
end
